version: "3"
services:
  # db:
  #   image: ghcr.io/tursodatabase/libsql-server:latest
  #   platform: linux/amd64
  #   ports:
  #     - "8080:8080"
  #     - "5001:5001"
  #   # environment:
  #   #   - SQLD_NODE=primary
  #   volumes:
  #     - ./sqld:/var/lib/sqld
  nuxt:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app